### ISSUE TITLE
Raise EOFError because train data in 'RL2S/l2s_dataset/hopper/train_data/' is 0 bytes.

### ISSUE THREAD

**Issue by qsa-fox** [apexrl/RL2S#1]

**Comment by qsa-fox** [comment]
Thanks for sharing the code. 
When I try to run the command 'python3 run_l2s.py -e exp_specs/l2s_hopper.yaml --nosrun -c 0' , a EOFError is raised, when checking the related files in  'RL2S/l2s_dataset/hopper/train_data/', are 0 bytes.
How to generated these train_data by myself ?

**Comment by destinyyzy** [comment]
You can use the rolloutSimMujoco function in rlkit/rlkit/samplers/l2s_sampler.py to generate some trajectories (a list of trajectories) and then save them as a pkl file.

**Comment by Ericonaldo** [comment]
Maybe more guidance for repeating the experiments or scripts can be committed to this repo. @destinyyzy

**Comment by destinyyzy** [comment]
I have been busy with interviews and thesis recently, after which I will upload the corresponding data collection scripts.

**Comment by destinyyzy** [comment]
I have added some guidance for date generation in README.
